import Lake
open Lake DSL

/-! The sources use the mathlib4 revision checked out during formalization. -/
require mathlib from git "https://github.com/leanprover-community/mathlib4.git" @ "5e932f97dd25535344f80f9dd8da3aab83df0fe6"

package bures where

/-! Every top-level research module is an explicit library root. This avoids
including the vendored `mathlib/` working checkout in the local library. -/
@[default_target]
lean_lib BuresAutomaticSurjectivity where
  roots := #[
    `Bures,
    `BuresAnchorDerivative,
    `BuresApexFourPoint,
    `BuresApexImageInterior,
    `BuresApexNotInteriorGeneral,
    `BuresApexTangentTransfer,
    `BuresAutomaticSurjectivity,
    `BuresCommutingProduct,
    `BuresCompletion,
    `BuresConeGeometry,
    `BuresConnectionAlgebra,
    `BuresCoordinateCurvature,
    `BuresCoordinatesCriterion,
    `BuresCurvatureAtIdentityAlgebra,
    `BuresExtension,
    `BuresFourPoint,
    `BuresFourPointGeneral,
    `BuresFrobenius,
    `BuresGeodesicRigidity,
    `BuresHorizontalLocal,
    `BuresImageAnchorCoordinates,
    `BuresImageSimplex,
    `BuresInfinitesimalMetric,
    `BuresInterior,
    `BuresInteriorFourPoint,
    `BuresInteriorTangent,
    `BuresIsometrySmoothPrelude,
    `BuresIsometrySmoothTangent,
    `BuresLocalRegularity,
    `BuresMetric,
    `BuresMetricAudit,
    `BuresMetricHomogeneity,
    `BuresMetricSimplexStability,
    `BuresMetricTangents,
    `BuresMidpointIteration,
    `BuresNoncommuting,
    `BuresNormComparison,
    `BuresNormalBlowdown,
    `BuresNormalChart,
    `BuresNormalForm,
    `BuresNormalIsometry,
    `BuresNormalLinearExtension,
    `BuresNormalNormalization,
    `BuresNormalTangent,
    `BuresOptimalLift,
    `BuresOptimalLiftJointSmooth,
    `BuresOptimalLiftSmooth,
    `BuresPSD,
    `BuresPSDMetric,
    `BuresQubitFidelity,
    `BuresQubitTangent,
    `BuresQubitUnitary,
    `BuresQuotientGeodesic,
    `BuresQuotientPathLength,
    `BuresRadial,
    `BuresRadicand,
    `BuresRankOneFourPoint,
    `BuresSeparation,
    `BuresShiftStrict,
    `BuresShiftTrace,
    `BuresSquareDerivative,
    `BuresSquareTranslation,
    `BuresSquaredSmooth,
    `BuresSymmetry,
    `BuresTopology,
    `BuresTranslationRigidity,
    `BuresTriangle,
    `BuresUniqueGeodesic,
    `BuresVariational,
    `BuresVerticalBracket,
    `CompactSurjectivity,
    `HermitianFiniteDimension,
    `HermitianSquareSmooth,
    `HermitianSylvesterSmooth,
    `IsometryExtension,
    `RadialAlgebra,
    `RadialScaleRigidity,
    `Sylvester,
    `TraceCompactness
  ]
